In [9]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#-------------------------------------------------------------------------------------------
#loading the dataset
retail_df = pd.read_excel("/Users/manesh/Documents/Manesh /Masters/Portfolios/uk-retail-customer-analytics/Data/Online Retail.xlsx")
#-------------------------------------------------------------------------------------------

#examin the dataset data strutre

#preview first 5 rows
display(retail_df.head())

print()

#preview last 5 rows
display(retail_df.tail())

print()

#examin dataset dimensions
print("dataset shape: ", retail_df.shape)
print("dataset num of rows", retail_df.shape[0])
print("dataset num of cols",retail_df.shape[1] )

print()

#examin the col names
print("\nColumn names: ")
print(retail_df.columns.tolist)

print()
#-------------------------------------------------------------------------------------------
#examin the data types and the non-null count of the dataset
print("\nDataset Information: ")
retail_df.info()

print()

#dataset datatypes
print("\nDataset datatypes: ")
print(retail_df.dtypes)

print()
#-------------------------------------------------------------------------------------------
#statistical summary of the dataset
display(retail_df.describe())

print()

#statistical summary including categorical columns
display(retail_df.describe(include="all").T)

print()
#-------------------------------------------------------------------------------------------
#check the number unique values in each column 
unique_values = retail_df.nunique().sort_values

print(unique_values)

#checking the unique values of each columns 

uniqe_description = retail_df["Description"].unique()
unique_stockcode = retail_df["StockCode"].unique()
unique_country = retail_df["Country"].unique()

print("\nUnique descriptions: ")
print(uniqe_description)

print("\nUnique stockcodes: ")
print(unique_stockcode)

print("\nunique country: ")
print(unique_country)

#check unique values with their frequencies 
unique_description_freq = retail_df["Description"].value_counts()
unique_stockcode_freq = retail_df["StockCode"].value_counts()
unique_country_freq = retail_df["Country"].unique()

print("\nUnique descriptions frequencies:")
print(unique_description_freq)

print("\nUnique stockcodes frequencies:")
print(unique_stockcode_freq)

print("\nUnique Country frequencies: ")
print(unique_country_freq)

#check propotion of unique value frequencies 
desc_freq_prop = retail_df["Description"].value_counts(normalize= True)
stockcode_freq_prop = retail_df["StockCode"].value_counts(normalize= True)
country_freq_prop = retail_df["Country"].value_counts(normalize= True)

print("\nUnique descriptions frequencies proportions:")
print(desc_freq_prop)

print("\nUnique stockcode frequencies proportions:")
print(stockcode_freq_prop)

print("\nUnique country frequencies proportions:")
print(country_freq_prop)

#Cardinality summary of dataset
cardinality_summary = pd.DataFrame(
    {
        "Data Type": retail_df.dtypes,
        "Unique Values" : retail_df.nunique(),
        "Missing Values" : retail_df.isnull().sum()

    }
) 

cardinality_summary = cardinality_summary.sort_values(
    by = "Unique Values"
)

print("\nCardinality Summary: ")
display(cardinality_summary)

#-------------------------------------------------------------------------------------------
#Missing values Identification =================================================

#checking missing values per column
missing_values_per_col = retail_df.isnull().sum()

print("\nMissing Values Per Columns: ")
print(missing_values_per_col)

#missing value percentage per column
miss_val_per = retail_df.isnull().sum() / len(retail_df) *100

print("\nMissing Value Percentage per column: ")
print(miss_val_per)

#missing value summary 
missing_summary = pd.DataFrame(
    {
        "Missing_Count" : retail_df.isnull().sum(),
        "Missing_Percentage" : (
            miss_val_per
        )
    }
)

#show the columns containing missing values 
missing_summary = missing_summary [
    missing_summary["Missing_Count"] > 0
]

#Sort highest to Lowest 
missing_summary = missing_summary.sort_values(
    by="Missing_Percentage", 
    ascending = False
)

print("\nMisisng Value Summary: ")
display(missing_summary)

#Check the total missing value count of the dataset 
total_missing = retail_df.isnull().sum().sum()
print("Total Missing Values are : ", total_missing)

#final check on dataset contains any missing value 
Any_miss_val_check = retail_df.isnull().values.any()
print("Any missing values: ", Any_miss_val_check)

#count the rows contains at least one missing value
rows_with_missing = retail_df.isnull().any(axis=1).sum()
print("Rows with missing: ", rows_with_missing)

#handling missing values -----------------------------------
# Fill missing Description values
retail_df["Description"].fillna("Unknown")

#remove rows with missing customer IDs
retail_df = retail_df.dropna(subset=["CustomerID"])

#reset dataset index after dropping rows 
retail_df = retail_df.reset_index(drop=True)

#Validation of the missing values handling
print("\nMissing Values After Handling: ")
print(retail_df.isnull().sum())


print("\nDataset shape after handling missing values: ")
print(retail_df.shape)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

dataset shape:  (541909, 8)
dataset num of rows 541909
dataset num of cols 8


Column names:
<bound method IndexOpsMixin.tolist of Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')>


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


Dataset datatypes:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
InvoiceNo,541909.0,25900.0,573585.0,1114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockCode,541909,4070,85123A,2313,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,540455,4223,WHITE HANGING HEART T-LIGHT HOLDER,2369,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,541909.0,NaN,NaN,NaN,9.55225,-80995.0,1.0,3.0,10.0,80995.0,218.081158
InvoiceDate,541909,NaN,NaN,NaN,2011-07-04 13:34:57.156386048,2010-12-01 08:26:00,2011-03-28 11:34:00,2011-07-19 17:17:00,2011-10-19 11:27:00,2011-12-09 12:50:00,NaN
UnitPrice,541909.0,NaN,NaN,NaN,4.611114,-11062.06,1.25,2.08,4.13,38970.0,96.759853
CustomerID,406829.0,NaN,NaN,NaN,15287.69057,12346.0,13953.0,15152.0,16791.0,18287.0,1713.600303
Country,541909,38,United Kingdom,495478,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<bound method Series.sort_values of InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64>

Unique descriptions:
['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' ... 'lost'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']

Unique stockcodes:
['85123A' 71053 '84406B' ... '90214U' '47591b' 23843]

unique country:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

Unique descriptions frequencies:
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
Marked as 23343                          1
20713                                    1
HEAVENS SCENT FRAGRANCE OILS ASSTD       1
BLUE DROP EARRINGS W BEAD CLUSTER        1
PURPLE ANEMONE ARTIFICIAL FLOWER         1
Name: count, Length: 4223, dtype: int64

Unique stockcodes frequencies:
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
23664        1
23617        1
90214U       1
47591b       1
23602        1
Name: count, Length: 4070, dtype: int64

Unique Country frequencies:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

Unique descriptions frequencies proportions:
Description
WHITE HANGING HEART T-LIGHT HOLDER    0.004383
REGENCY CAKESTAND 3 TIER              0.004071
JUMBO BAG RED RETROSPOT               0.003995
PARTY BUNTING                         0.003195
LUNCH BAG RED RETROSPOT               0.003031
                                        ...
Marked as 23343                       0.000002
20713                                 0.000002
HEAVENS SCENT FRAGRANCE OILS ASSTD    0.000002
BLUE DROP EARRINGS W BEAD CLUSTER     0.000002
PURPLE ANEMONE ARTIFICIAL FLOWER      0.000002
Name: proportion, Length: 4223, dtype: float64

Unique stockcode frequencies proportions:
StockCode
85123A    0.004268
22423     0.004065
85099B    0.003984
47566     0.003187
20725     0.003024
            ...
23664     0.000002
23617     0.000002
90214U    0.000002
47591b    0.000002
23602     0.000002
Name: proportion, Length: 4070, dtype: float64

Unique country frequencies proportions:
Country
United Kingdom          0.914320
Germany                 0.017521
France                  0.015790
EIRE                    0.015124
Spain                   0.004674
Netherlands             0.004375
Belgium                 0.003818
Switzerland             0.003694
Portugal                0.002803
Australia               0.002323
Norway                  0.002004
Italy                   0.001482
Channel Islands         0.001399
Finland                 0.001283
Cyprus                  0.001148
Sweden                  0.000853
Unspecified             0.000823
Austria                 0.000740
Denmark                 0.000718
Japan                   0.000661
Poland                  0.000629
Israel                  0.000548
USA                     0.000537
Hong Kong               0.000531
Singapore               0.000423
Iceland                 0.000336
Canada                  0.000279
Greece                  0.000269
Malta                   0.000234
United Arab Emirates    0.000125
European Community      0.000113
RSA                     0.000107
Lebanon                 0.000083
Lithuania               0.000065
Brazil                  0.000059
Czech Republic          0.000055
Bahrain                 0.000035
Saudi Arabia            0.000018
Name: proportion, dtype: float64

Cardinality Summary:

                  Data Type  Unique Values  Missing Values
Country              object             38               0
Quantity              int64            722               0
UnitPrice           float64           1630               0
StockCode            object           4070               0
Description          object           4223            1454
CustomerID          float64           4372          135080
InvoiceDate  datetime64[ns]          23260               0
InvoiceNo            object          25900               0

Missing Values Per Columns:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing Value Percentage per column:
InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

Misisng Value Summary:

             Missing_Count  Missing_Percentage
CustomerID          135080           24.926694
Description           1454            0.268311

Total Missing Values are :  136534
Any missing values:  True
Rows with missing:  135080

Missing Values After Handling:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Dataset shape after handling missing values:
(406829, 8)